[build]
  publish = "public"

[[redirects]]
  from = "/email-preview/*"
  to = "/email-preview/index.html"
  status = 200

[[redirects]]
  from = "/api/*"
  to = "https://savepulse-backend.onrender.com/api/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200