[build]
  publish = "public"
  ignore = "git diff --quiet $CACHED_COMMIT_REF $COMMIT_REF public/ netlify.toml"

[[redirects]]
  from = "/email-preview/*"
  to = "https://savepulse-backend.onrender.com/email-preview/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/email-preview"
  to = "https://savepulse-backend.onrender.com/email-preview"
  status = 200
  force = true

[[redirects]]
  from = "/api/*"
  to = "https://savepulse-backend.onrender.com/api/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
